### PR TITLE
DEV-199 Update pd-cap-recipes to Skip Flags for Git and Hipchat

### PR DESCRIPTION
**Pull request by robottaway**
Adding code to skip doing tasks (tasks will still show as run in Cap output) when appropriate flags set.

### CODE REVIEW

**Comment by esigler** [comment]
(Obligatory reminder for other participants, this is a public repo!)

Given the existing logic, LGTM!

@alperkokmen any comments?

**Comment by alperkokmen** [comment]
assuming we have tested it with the repo that necessitated the change, :shipit: – at some point, we will need other repos (e.g. `web`) to upgrade.

**Comment by robottaway** [comment]
@alperkokmen tested it with rt-legoland, with flags on/off without issues.

**Comment by alperkokmen** [comment]
@robottaway :+1:

**Pull request merged**
