### PR TITLE
Remove dependency on mysql

### PR DESCRIPTION
**Pull request by robottaway**

### CODE REVIEW

**Comment by esigler** [comment]
Sweet, LGTM.  @alperkokmen or @ranjib any preference on bumping rev?

**Comment by ranjib** [comment]
nope we are already on a different release train, i think we are good.

**Comment by ranjib** [comment]
:+1:

**Comment by robottaway** [comment]
I will look up those release instructions and get this out. I'll have to release a new rt-cap-deploy today as well to ensure that numerator will be releasable via GoCD (to staging).

**Pull request merged**
